### ISSUE TITLE
Laravel Sail

### ISSUE THREAD

**Issue by sdapkus** [tighten/laravelm1#8]
[Docker RC1](https://docs.docker.com/docker-for-mac/apple-m1/) for m1 is here, with it is possible to install docker.

I've tried setting up [Laravel Sail](https://laravel.com/docs/8.x/sail#introduction) (not mentioned in your docs), basic stack (php 7.4, mysql 8, redis and mailhog) works with one simple change - `platform: linux/x86_64` setting needs to be added to mysql docker-compose file.

**Comment by iSWORD** [comment]
Adding the platform allowed sail to get unstuck but now I'm getting a segfault while installing node in the sail image.

<details>
  <summary>Log</summary>
  
```
#8 319.9 Get:1 https://deb.nodesource.com/node_15.x focal/main arm64 nodejs arm64 15.14.0-deb-1nodesource1 [24.8 MB]
#8 323.8 debconf: delaying package configuration, since apt-utils is not installed
#8 323.8 Fetched 24.8 MB in 4s (5898 kB/s)
#8 323.9 Selecting previously unselected package nodejs.
(Reading database ... 21562 files and directories currently installed.)
#8 323.9 Preparing to unpack .../nodejs_15.14.0-deb-1nodesource1_arm64.deb ...
#8 324.0 Unpacking nodejs (15.14.0-deb-1nodesource1) ...
#8 326.2 Setting up nodejs (15.14.0-deb-1nodesource1) ...
#8 326.5 Processing triggers for man-db (2.9.1-1) ...
#8 326.9 Warning: apt-key output should not be parsed (stdout is not a terminal)
#8 327.2 Segmentation fault
#8 327.2 gpg: no valid OpenPGP data found.
```
</details>

**Comment by sdapkus** [comment]
Not sure about this. For me installing npm inside container worked.

**Comment by iSWORD** [comment]
I tried multiple times without any luck. Do you remember making any other changes to `docker-compose.yml` or other files?

**Comment by sdapkus** [comment]
As I wrote before, I'm using php 7.4, so from default sail docker-compose, I've changed php version. And added extra volume, to mount local ssh keys to container.

```yaml
# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/7.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-7.4/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
            - '~/.ssh:/home/sail/.ssh:ro'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        platform: linux/x86_64
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
```
